### PR TITLE
Jacobi Preconditioner

### PR DESCRIPTION
**Pull request by nathanielpritchard**
Added the Jacobi preconditioner and relevant tests:
- Styled after the sor implementation
- Compute iteration by accumulating values in a column vector owing to column oriented nature of julia matrices.

### CODE REVIEW

**Comment by dmaldona** [comment]
@npritch928 Just merged the SOR preconditioner but this branch has some conflicts now. Perhaps you want to rebase.

**Comment by nathanielpritchard** [comment]
@dmaldona  I think its just an issue that runtest.jl and LSPreconditioners.jl files had the include statements and jacobi in the same spot. I have now corrected this though.

**Comment by dmaldona** [comment]
@npritch928 sorry about the delay in responding, dont know why i dont get your updates.

I am still seeing the conflict. Here's a screenshot of what I am referring to

image

**Comment by nathanielpritchard** [comment]
I think this time the change has actually been corrected. I keep trying to use the resolve branch feature on github and think I may not have saved last time.

**Pull request merged**
